{{- define "canary-weight" }}{{ if .Values.ascii.canary }}weight: {{.Values.ascii.canary}}{{ end }} {{- end }}
{{- define "canary-header" }}{{ if .Values.ascii.header  }}headers:{{ end }} {{- end }}
{{- define "canary-header-mode" }}{{ if .Values.ascii.header  }}x-mode: {{ .Values.ascii.header }}{{ end }} {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ascii
  namespace: {{ .Release.Namespace }}
  labels:
    app: ascii
    version: {{ .Values.app.version }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.ascii.port }}
  selector:
    app: {{ .Release.Name }}-ascii
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "helm.fullname" . }}-ascii
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGateway }}
  hostnames:
    - {{ .Values.gateway.hostname | quote }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Release.Name }}-ascii
      port: {{ .Values.app.port }}
      weight: 1
    {{- with .Values.filters }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gateway.path }}ascii