---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  ports:
  - name: tcp-mysql
    port: 3306
    targetPort: 3306
  selector:
    app: {{ .Release.Name }}-mysql
